In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('diabetes.csv')

In [3]:
df.shape

(768, 9)

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
# checking null values
df.isnull().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [11]:
zero_not_allowed=['Glucose','BloodPressure','SkinThickness','Insulin']

In [12]:
for column in zero_not_allowed:
    df[column]=df[column].replace(0,np.nan)
    mean = int(df[column].mean(skipna=True))
    df[column]= df[column].replace(np.nan,mean)

In [13]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0           72.0           35.0    155.0  33.6   
1            1     85.0           66.0           29.0    155.0  26.6   
2            8    183.0           64.0           29.0    155.0  23.3   
3            1     89.0           66.0           23.0     94.0  28.1   
4            0    137.0           40.0           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
df['Insulin']

0        0
1        0
2        0
3       94
4      168
      ... 
763    180
764      0
765    112
766      0
767      0
Name: Insulin, Length: 768, dtype: int64

In [15]:
x = df.iloc[:,:-2]
y = df.iloc[:,-1]

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
model = SVC(kernel='linear')

In [25]:
model.fit(x_train,y_train)

SVC(kernel='linear')

In [26]:
y_pred = model.predict(x_test)

In [29]:
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.7987012987012987


In [30]:
confusion_matrix(y_test,y_pred)

array([[96, 11],
       [20, 27]], dtype=int64)

In [31]:
model = SVC(kernel='rbf')

In [32]:
model.fit(x_train,y_train)

SVC()

In [33]:
y_pred = model.predict(x_test)

In [34]:
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.7857142857142857


In [35]:
confusion_matrix(y_test,y_pred)

array([[97, 10],
       [23, 24]], dtype=int64)

In [39]:
x = df.drop(['Outcome','Insulin'],axis=1)
y = df['Outcome']

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [41]:
model = SVC(kernel='linear')

In [42]:
model.fit(x_train,y_train)

SVC(kernel='linear')

In [43]:
y_pred = model.predict(x_test)

In [44]:
print('Accuracy :',accuracy_score(y_test,y_pred))

Accuracy : 0.8116883116883117


In [45]:
confusion_matrix(y_test,y_pred)

array([[97, 10],
       [19, 28]], dtype=int64)