# HOLD OUT

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
X = [10,20,30,40,50,60,70,80,90,100]
X_train, X_test= train_test_split(X,test_size=0.3, random_state=1)
print("Train:",X_train,"Test:" ,X_test)

Train: [50, 10, 40, 20, 80, 90, 60] Test: [30, 100, 70]


# lEVE OUT

In [3]:
from sklearn.model_selection import LeaveOneOut


In [4]:
X = [10,20,30,40,50,60,70,80,90,100]

l = LeaveOneOut()

for train, test in l.split(X):

    print("%s %s"% (train,test))

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


# K-Fold Cross-Validation

In [5]:
from sklearn.model_selection import KFold


In [6]:
X = ["a",'b','c','d','e','f']

kf = KFold(n_splits=3, shuffle=False, random_state=None)

for train, test in kf.split(X):

    print("Train data",train,"Test data",test)

Train data [2 3 4 5] Test data [0 1]
Train data [0 1 4 5] Test data [2 3]
Train data [0 1 2 3] Test data [4 5]


# Stratified K-Fold Cross-Validation


In [7]:
from sklearn.model_selection import StratifiedKFold
import numpy as np

In [8]:
X = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y= np.array([0,0,1,0,1,1])

skf = StratifiedKFold(n_splits=3,random_state=None,shuffle=False)

for train_index,test_index in skf.split(X,y):
    print("Train:",train_index,'Test:',test_index)
    X_train,X_test = X[train_index], X[test_index]
    y_train,y_test = y[train_index], y[test_index]

Train: [1 3 4 5] Test: [0 2]
Train: [0 2 3 5] Test: [1 4]
Train: [0 1 2 4] Test: [3 5]
